@startuml Onboard Account Flow

autonumber "<b>[0]"
actor Client
box ROC
participant "Techcombank Mobile" as TCB
participant "Edge" as EDGE
participant "arrangement-manager-extension" as AME
participant "user-manager-dis" as UMD
participant "confirmation-service" as CMS
participant "identity-service" as IDS
participant "biometric-service" as BMS
participant "ingestion-service" as ING
database "arrangement-manager-extension" as DB
end box
participant "EKYC" as EKYC
participant "ECM" as ECM
participant "Mule Internal" as MI
participant "T24" as T24
participant "Mule External" as ME
participant "CurrencyCloud" as CC

Client -> TCB: Create visa cross border account
TCB -> EDGE: Request get list currency\nGET /client-api/v1/visaxborder/create-account
EDGE -> EDGE: Check JWT token
alt Auth failed
    EDGE --> TCB: Return 401 Unauthorized
    TCB --> Client: Display error message
end
EDGE -> AME: Forward
activate AME
AME -> UMD: GET /service-api/v2/customer/user-info
activate UMD
UMD --> AME: Return result
deactivate UMD
AME -> AME: Validate customer info
AME -> CMS: Create unfinalize confimation
activate CMS
CMS --> AME: Return confirmationId
deactivate CMS
AME -> DB: Insert visa-account-request\nconfirmationId = confirmationId return from step 11\nstatus = PENDING_CONFIRM
activate DB
DB --> AME: Return result
deactivate DB
AME -> EDGE: Return unauthorized, request transaction signing
deactivate AME
EDGE --> TCB: Forward
TCB -> IDS: Transaction signing
activate IDS
IDS --> AME: Call back to arrangement service\nPATCH /service-api/v1/visaxborder/confirmation/{confirmationId}
deactivate IDS
activate AME

note right of AME
Step 1: Query data from table <b>visa-account-request</b>
end note
AME -> DB: Query <b>visa-account-request</b> by confirmationId
activate DB
DB --> AME: Return result
deactivate DB

note right of AME
Step 2: Query join data from table <b>visa-account-link</b> & <b>visa_funding_account</b> continue process
end note
AME -> DB: Query data by customerId and currency
activate DB
DB --> AME: Return result
deactivate DB
alt Record not found for currency request
    note right of AME
    Step 3: Call find funding account API from CurrencyCloud
    end note
    AME -> ME: Find funding account in CurrencyCloud
    activate ME
    note right of ME
    Before proceeding to Step 2, ensure valid CurrencyCloud token.
    end note
    ME -> CC: GET /v2/funding_accounts/find param: account_id, currency
    activate CC
    alt API call success
    else API call failed
        CC --> ME: Return error
        deactivate CC
        ME --> AME: Return error
        deactivate ME
        AME --> TCB: Return error
        deactivate AME
        TCB --> Client: Display error message
    end


else Record found for currency request
end

@enduml
